# Generated by Django 4.0.4 on 2022-06-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('EMOTIONS', models.CharField(choices=[('neutral', 'neutral'), ('joy', 'joy'), ('sadness', 'sadness'), ('disgust', 'disgust'), ('fear', 'fear'), ('surprise', 'surprise'), ('anger', 'anger'), ('shame', 'shame'), ('disgust', 'disgust')], max_length=10)),
                ('SID', models.CharField(max_length=255)),
            ],
        ),
    ]
